# Generated by Django 5.0.1 on 2025-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('awb', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=50)),
                ('assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('vapi_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call History',
                'verbose_name_plural': 'Call Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
