# Generated by Django 5.0.1 on 2025-11-15 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_type', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_scan', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['order_type', '-updated_at'], name='orders_orde_order_t_f699f6_idx'), models.Index(fields=['synced_at'], name='orders_orde_synced__9d079b_idx')],
            },
        ),
    ]
