# Generated by Django 5.0.1 on 2025-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='is_successful',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='needs_retry',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='awb',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='customer_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['awb', '-created_at'], name='orders_call_awb_4fac7e_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['customer_phone', '-created_at'], name='orders_call_custome_0a7581_idx'),
        ),
    ]
