# Generated by Django 4.2.7 on 2025-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_callhistory_is_successful_callhistory_needs_retry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
