# Generated by Django 4.2.7 on 2025-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_callhistory_recording_url_callhistory_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='callhistory',
            name='transcript',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['awb'], name='orders_orde_awb_bf3f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'current_status'], name='orders_orde_order_t_84f29e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_mobile'], name='orders_orde_custome_8dcbe8_idx'),
        ),
    ]
